// Candidate identity from the member's config/profile.yml (generated by Compass).
import * as yaml from 'js-yaml';

export function parseProfile(profileYaml) {
  let p = {};
  try { p = yaml.load(profileYaml || '') || {}; } catch { p = {}; }
  const c = p.candidate || {};
  const str = (v) => (v == null ? '' : String(v).trim());
  return {
    raw: p,
    name: str(c.full_name), email: str(c.email), phone: str(c.phone), location: str(c.location),
    linkedin: str(c.linkedin), github: str(c.github), portfolio: str(c.portfolio_url),
    targetRoles: Array.isArray(p.target_roles?.primary) ? p.target_roles.primary.map(str).filter(Boolean) : [],
    targetRange: str(p.compensation?.target_range), minimum: str(p.compensation?.minimum),
    country: str(p.location?.country),
  };
}

export const kebab = (s) => String(s || '').toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'candidate';
